In [1]:
# 1. Numpyで一次配列(文字列型＝デフォルト)を作成
import numpy as np
arr = np.asarray(input().rstrip().split(' '))
print(arr)

2 3 4 
['2' '3' '4']


In [2]:
# 2. Numpyで一次配列(数値型)を作成
import numpy as np
arr = np.asarray(input().rstrip().split(' '), dtype=np.int32)
print(arr)

2 3 4 7 6 5
[2 3 4 7 6 5]


In [14]:
# 3. Numpyで二次配列(数値型)を作成
import numpy as np
# N - 列数
N = int(input())

arr = np.asarray(([input().rstrip().split(' ') for i in range(N)]), dtype=np.int32)
print(arr)

2
1 2
2 3
[[1 2]
 [2 3]]


In [15]:
# 4. Numpyで要素が全部0の配列を作成
import numpy as np

# 入力した形(x行y列)の全要素0配列を作成
sp = input().rstrip().split(' ')
x = int(sp[0])
y = int(sp[1])
arr = np.zeros((x, y))
print(arr)

1 2
[[ 0.  0.]]
